# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/repository/docker/tongngochuunghia/openjdk-nodejs
image: node:16.14.2

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  MATTERMOST_WEBHOOKS_URL: "https://mattermost.gss-sol.com/hooks/39ri61rgefb4bdf1o98n7i5h4o"

before_script:
  # Install pnpm
  - npm install -g pnpm
  # Check environment before start pipeline
  - node -v && npm -v && pnpm -v
  # Install node_module & build css+js
  - pnpm install

stages:
  - build

build:
  stage: build
  tags:
    - linux
  only:
    - master
    - release
    - develop
    - merge_requests
  script:
    - cp -f .env.production .env
    # Build and send report to mattermost
    - >
      pnpm lint && pnpm build &&
        curl -XPOST -H "Content-type: application/json" -d "{\"attachments\": [{\"color\": \"#00cc00\",\"title\": \"GPS-WEB-TR PIPELINE SUCCESS\",\"text\": \"**To:** @${GITLAB_USER_LOGIN} - **commit:** [#${CI_COMMIT_SHORT_SHA}](https://gitlab.gss-sol.com/tanaak/gps-web-tr/-/commit/${CI_COMMIT_SHA}), **branch:** ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}, **message:** ${CI_COMMIT_MESSAGE}\"}]}" "${MATTERMOST_WEBHOOKS_URL}" ||
        (curl -XPOST -H "Content-type: application/json" -d "{\"attachments\": [{\"color\": \"#ff0000\",\"title\": \"GPS-WEB-TR PIPELINE FAILED\",\"text\": \"**To:** @${GITLAB_USER_LOGIN} - **commit:** [#${CI_COMMIT_SHORT_SHA}](https://gitlab.gss-sol.com/tanaak/gps-web-tr/-/commit/${CI_COMMIT_SHA}), **branch:** ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}, **message:** ${CI_COMMIT_MESSAGE}\"}]}" "${MATTERMOST_WEBHOOKS_URL}" && exit 1)

after_script:
  - echo "Pipeline finished!"
