version: '3.3'

volumes:
  nginx-logs: null

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - nginx-logs:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
